### ISSUE TITLE
Clarity on first-time UX

### ISSUE THREAD

**Issue by yualan** [BateleurIO/sqlops-combine-scripts#1]
I am working on providing a first-time UX blog post of this extension, but I am having issues with exposing this functionality.

![image](https://user-images.githubusercontent.com/30873802/42895413-ba0ab41c-8a6e-11e8-9bcc-351251d29f02.png)

Is this the target location for the extension? I have also tried selecting SQL files and running 'Combine Scripts' through the command palette (CTRL+SHIFT+P). Any advice would be appreciated.

**Comment by CobusKruger** [comment]
Hi, thank you for reaching out!

I somehow managed to lose the menu item in my last update. I'll push
tonight. As soon as the PR is accepted, I'll let you know.

Thanks again, and we'll speak soon.

Regards,

Cobus Kruger

**Comment by yualan** [comment]
Hi Cobus, sounds good. As an FYI, we are pushing a new release of SQL Operations Studio out that includes the extension tomorrow, which includes a release blog that highlights things like new extensions. I wanted to include yours, so if you have additional content outside the readme to share, feel free to let me know. This can include screenshots. 

The caveat is that I will be submitting a draft that will be onboarded this afternoon, meaning we may not be able to get your content on the blog exactly by tomorrow's publish. We can certainly try :) Thanks for contributing and excited for the new features in this extension!

**Comment by CobusKruger** [comment]
@yualan I've created my new release and updated the PR for it, so it should be good to go. Also, we can take off the Preview glyph.

You asked about UX...

I added a new menu item on the tree:
![image](https://user-images.githubusercontent.com/10893522/42905204-999891b8-8ad7-11e8-9749-3600d3c30de6.png)

You can use Ctrl and Shift to multi-select not only SQL files, but entire folders. When you then click Combine Scripts, all the SQL files are iterated and combined into one large script, which is easier to work with,

**Comment by yualan** [comment]
This is perfect. I'll go double check with our engineer managing our Extensions Manager.Thank you so much. I am sure you have already reached out to our team, but feel free to provide any feedback about your extension creation experience.
