### ISSUE TITLE
Need to put a GO statement between PRINT and CREATE

### ISSUE THREAD

**Issue by Colizobble** [BateleurIO/sqlops-combine-scripts#2]
The script adds PRINT statements before the start of each combined file, but doesn't put a GO statement between the PRINT and a following CREATE.

**Comment by CobusKruger** [comment]
That's a great suggestion. I'll try to get that in this weekend.

**Comment by CobusKruger** [comment]
@Colizobble I've created a release (1.3.0), which you can install directly. I don't have a feel for how long it will take to update in the Sqlops extension gallery.

The VS Code version should already be available.

**Comment by Colizobble** [comment]
Thank you very much for implementing this so quickly and pointing me to the VS Code version as well
