### ISSUE TITLE
feature request: variable script separator text

### ISSUE THREAD

**Issue by KitLemmonds** [BateleurIO/sqlops-combine-scripts#4]
It would be useful if the user could specify custom text to separate each script component instead of just the standard GO.  In my case, I like to separate each script component with an error check that sets NOEXEC on if an error is encountered : 

```SQL
IF @@error<>0 SET NOEXEC ON
GO
```

**Comment by CobusKruger** [comment]
@KitLemmonds that's a brilliant suggestion. I'll try to get to it this weekend.

**Comment by CobusKruger** [comment]
This is now available in version 2.0.0.

**Comment by KitLemmonds** [comment]
> This is now available in version 2.0.0.

The added functionality in the new version is extremely helpful.  In addition to the file separator, I used the file header and footer to add transaction logic to begin and commit/rollback the deployment script based on error status.  Thanks for the great extension!

**Comment by CobusKruger** [comment]
Thank you for the feedback and for the great idea.
